### ISSUE TITLE
When I click on cancel button it enter to callback function how I prevent this process? 

### ISSUE THREAD

**Issue by mostafamarji** [skwasjer/skwas-cordova-plugin-datetimepicker#12]

**Comment by skwasjer** [comment]
This is a bug on some Android versions because it is raising the positive click event also for cancel clicks, and so I had to handle the button clicks myself, which I only fixed last week. I have not fully finished and tested it yet so I did not release this yet on NPM, but it is fixed here: 

https://github.com/skwasjer/skwas-cordova-plugin-datetimepicker/blob/master/src/android/TimePickerDialog.java#L46,L57

You can try installing latest version for the time being:

cordova plugin add https://github.com/skwasjer/skwas-cordova-plugin-datetimepicker.git

I will release the next version via NPM soon when I have some more time.

**Comment by skwasjer** [comment]
Fixed in [v1.0.0](https://github.com/skwasjer/skwas-cordova-plugin-datetimepicker/releases/tag/v1.0.0)
