### ISSUE TITLE
iOS show nothing when skipped some options

### ISSUE THREAD

**Issue by obxyann** [skwasjer/skwas-cordova-plugin-datetimepicker#24]
It said "Note that not all options have to be set" but when I skipped 
allowOldDates, 	allowFutureDates, okText or cancelText anyone of them, it will throw:

<NSInvalidArgumentException> -[NSNull length]: unrecognized selector sent to instance 0x10ec....
at 
```
- (void)configureDatePicker:(NSMutableDictionary *)optionsOrNil datePicker:(UIDatePicker *)datePicker;
{
...
BOOL allowOldDates = [[optionsOrNil objectForKey:@"allowOldDates"] intValue] == 1 ? YES : NO;
BOOL allowFutureDates = [[optionsOrNil objectForKey:@"allowFutureDates"] intValue] == 1 ? YES : NO;
...
if (okTextString == nil || okTextString.length == 0) okTextString = @"Select";
if (cancelTextString == nil || cancelTextString.length == 0) cancelTextString = @"Cancel";
```
but no problem after assigned values (like example) to them!
I am not an iOS programmer so I don't know why or is this a bug or not (maybe my Cordova integrity)

P.S. I am using XCode 9.4.1 run in iPhone8 (11.4) emulator + Cordova 8.0.0 w/ cordova-ios 4.5.4

**Comment by skwasjer** [comment]
Thanks for reporting, I've had similar reports on this for other properties. The problem is the code that checks for nil where the reference seems to be NSNull. I am not aware when this problem started manifesting itself, but it seems something has significantly changed with newer SDK's/Xcode/Cordova because I've used this plugin (without those properties) myself in projects for over 4 years and it hadn't been an issue before. 

My best guess is it might have to do with the bridge between Cordova and native code, and serializing JSON differently now and the plugin just poorly handling this. The plugin uses some logic to validate/sanitize the settings, and using Javascript's `null` for uninitialized values as opposed to `undefined`. It would explain the bug if undefined->nil and null->NSNull, whereas in the past both may have been nil. Again, just a wild guess.

The good news is I already started reworking bits of code in the past few weeks on the develop branch, with some other fixes and new features, and so I hope to release an update somewhere in the near future that fixes it. Until then the workaround unfortunately is to provide those values.
