### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by jchavarria1983** [skwasjer/skwas-cordova-plugin-datetimepicker#31]
Hi, Im trying to use the plugin, I just copied and pasted the example in my project but no window is shown in screen. I just can see this object  in the console. 

DateTimePickerPlugin: Exec 'show' with: ObjectallowFutureDates: trueallowOldDates: trueandroid: Objectcancel: ()cancelText: "Cancel"date: Tue Aug 27 2019 01:48:41 GMT-0600 (CST)error: (err)locale: "EN"maxDate: nullminDate: Tue Aug 27 2019 01:48:41 GMT-0600 (CST)minDateTicks: 1566892121998minuteInterval: 15mode: "date"okText: "Select"success: (newDate)ticks: 1566892121998__proto__: Object

PLease someone help  me !!!!

**Comment by skwasjer** [comment]
Can you try and remove the line `maxDate: null,` and see if that helps?

**Comment by samiroquai** [comment]
Hi. I faced the same problem today on my Android phone. I've attached an Android studio debugger to a demo app running on my phone, just to see if I could get more information and I think I have a clue. I saw error messages related to the ZoneId class. I went inside the source code (DateTimePicker.java) and saw the following line

`	
private static final ZoneId _utcZone = ZoneId.of("UTC"); 
`

The doc says that it was added in API Level 26 (https://developer.android.com/reference/java/time/ZoneId). It's consistent with the requirements of this plugin (Readme, the plugin requires Android 8). 

My phone is equiped with an Android 6 setup. That's why it didn't work. I've tried on an Android 8 device => the picker works!

More info https://source.android.com/setup/start/build-numbers 

Am I correct? Is there any older versions of this plugin supporting Android 6?

**Comment by samiroquai** [comment]
Replying to myself... I've downgraded to an older revision:

https://github.com/skwasjer/skwas-cordova-plugin-datetimepicker/commit/4f801233c658e08f7ea1939ae04bdcb6859351c4

Works on my Android 6 phone. Now, I guess I'll need to review all the commits since then in order to know what has changed and the impact it has on my app.

**Comment by skwasjer** [comment]
@samiroquai correct, the plugin (v2.x) requires API level 26 / Android 8 ([changelog](https://github.com/skwasjer/skwas-cordova-plugin-datetimepicker/blob/master/CHANGELOG.md)). Since Playstore requirements for API level is level 26 atm, I decided for v2 it was a good time to bump API level for the plugin too.

 v1.1.3 still works with older versions but lacks some of the v2 fixes/improvements obviously.

**Comment by Crylion** [comment]
@skwasjer While I **personally** am with you in just supporting the newest versions of everything (I also usually update everything all the time), I still need compatibility with older Android version for any app that's actually viable for any kind of bigger userbase.
Especially because I always want to use the newest version of every library/plugin I use in the apps I do for work, I think it's a pity that I can't use your newest fixes and improvements just because of those compatibility issues :/

The API level requirements of the play store are only for the **target** sdk version, not the lowest supported API. In theory you could still support down to API level 9 (although I wouldn't recommend that :D) and still TARGET level 28 to be compliant with the newest play store requirements.

**Comment by skwasjer** [comment]
@Crylion fair enough, I have no problem lowering requirement, just have to find alternative for ZoneId/time zone related stuff. The problem was the previous version was producing incorrect date/times and min/max bounds for certain time zones, and I decided to fix it with newer API's.

[edit] and I admit it has been a while since I worked on this :)

**Comment by skwasjer** [comment]
I've pushed a change to `develop` (https://github.com/skwasjer/skwas-cordova-plugin-datetimepicker/commit/68962b40a921e0c09b64fc91055c76e707f115c5), please give it a try by installing the plugin directly from git:

`cordova plugin add https://github.com/skwasjer/skwas-cordova-plugin-datetimepicker.git#develop`

If this works, then I'll release a new version to NPM.

**Comment by Crylion** [comment]
Nice, works on both Android 6 and 7 :)
Thanks for your quick response!

**Comment by skwasjer** [comment]
Released v2.0.1 to NPM
